name: publish on github

on:
    push:
        branches:
            - main


jobs:
    publish-gpr:
        runs-on: ubintu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 18
                registry-url: https://npm.pkg.github.com/
                scope: "@marija-kov"
            - run: npm install
            - run: npm run test
            - run: npm run build
            - run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

                